name: 記事・構成の改善提案
description: ドキュメント構成や表現の改善提案を送信します
title: "[提案] "
labels: ["enhancement"]
assignees: mii-10, takumi0213
body:
  - type: markdown
    attributes:
      value: |
        ✨ **追加・改善してほしいページについて教えてください。**
  
  - type: textarea
    id: summary
    attributes:
      label: 提案内容
      placeholder: 例）command/gchat に送信例のセクションを追加したい
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: 提案の背景・理由
      placeholder: 例）実際の使用例があると読み手が理解しやすくなるため

  - type: textarea
    id: related
    attributes:
      label: 関連ページ（任意）
      placeholder: 関連するMarkdownファイルなど
